---
- name: pull a docker file from remote repository
  hosts: local
  vars:
    ansible_python_interpreter: /usr/local/bin/python3


  tasks:  
    - name: Test Docker
      shell: docker --version
    # - name: Install docker python package
    #   pip: 
    #     name: docker 
    #     state: present 
    #     executable: pip3     
    
    - name: Pull calcspe-pipeline
      shell: docker pull ericjohneastwood/calcspe-pipeline:latest

    - name: Create container Calc
      shell: docker create -i -t --name calc ericjohneastwood/calcspe-pipeline

    -name: Start container Calc
      shell: docker start calc

